apiVersion: 1

contactPoints:
  - orgId: 1
    name: datapulse-webhook
    receivers:
      - uid: datapulse-webhook-uid
        type: webhook
        settings:
          url: http://api:8000/webhook/receiver
          httpMethod: POST
          title: "DataPulse Alert"
          message: "{{ template \"default.message\" . }}"
