"""
Contract definitions for the healthcare_analytics pipeline.

Defines expected schemas, freshness, and quality rules for
the source (bronze) and target (gold) datasets.
"""

# ── Source: bronze admissions (CSV generated by generate_healthcare_data.py) ──

ADMISSIONS_SOURCE_SCHEMA = {
    "admission_id": {"type": "string", "nullable": False},
    "patient_id": {"type": "string", "nullable": False},
    "hospital_id": {"type": "string", "nullable": False},
    "department_name": {"type": "string", "nullable": False},
    "doctor_id": {"type": "string", "nullable": False},
    "admission_date": {"type": "string", "nullable": False},
    "discharge_date": {"type": "string", "nullable": True},
    "admission_type": {"type": "string", "nullable": False},
    "discharge_status": {"type": "string", "nullable": False},
    "diagnosis_code": {"type": "string", "nullable": False},
    "severity": {"type": "string", "nullable": False},
    "total_cost": {"type": "string", "nullable": False},
    "insurance_id": {"type": "string", "nullable": False},
    "room_number": {"type": "string", "nullable": True},
    "bed_number": {"type": "string", "nullable": True},
}

ADMISSIONS_SOURCE_FRESHNESS = {
    "max_age_hours": 72,  # 3 days — batch pipeline, not real-time
    "timestamp_column": "admission_date",
}

ADMISSIONS_SOURCE_QUALITY = {
    "unique_keys": ["admission_id"],
    "min_row_count": 1000,
    "max_row_count": 200000,
    "max_row_count_diff_pct": 5,
}

# ── Target: fact_admission (dbt gold output) ──

FACT_ADMISSION_TARGET_SCHEMA = {
    "admission_id": {"type": "integer", "nullable": False},
    "patient_sk": {"type": "integer", "nullable": False},
    "hospital_sk": {"type": "integer", "nullable": False},
    "department_sk": {"type": "integer", "nullable": False},
    "doctor_sk": {"type": "integer", "nullable": False},
    "admission_date": {"type": "date", "nullable": False},
    "discharge_date": {"type": "date", "nullable": True},
    "admission_type": {"type": "string", "nullable": False},
    "discharge_status": {"type": "string", "nullable": False},
    "diagnosis_code": {"type": "string", "nullable": False},
    "severity": {"type": "string", "nullable": False},
    "total_cost": {"type": "decimal", "nullable": False},
    "insurance_sk": {"type": "integer", "nullable": False},
    "length_of_stay_days": {"type": "integer", "nullable": True},
}

FACT_ADMISSION_TARGET_FRESHNESS = {
    "max_age_hours": 72,
    "timestamp_column": "admission_date",
}

FACT_ADMISSION_TARGET_QUALITY = {
    "unique_keys": ["admission_id"],
    "min_row_count": 1000,
    "max_row_count": 200000,
    "max_row_count_diff_pct": 5,
}


# ── Pipeline metadata ──

PIPELINE_NAME = "healthcare_analytics"
PIPELINE_OWNER = "data-platform"
