"""initial_schema

Revision ID: e66e588be05f
Revises: 
Create Date: 2026-08-18 21:38:58.616638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66e588be05f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'name', name='uq_dataset_per_pipeline')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'RUNNING', 'PASSED', 'FAILED', 'LATE', name='runstatus'), nullable=False),
    sa.Column('source_row_count', sa.Integer(), nullable=True),
    sa.Column('target_row_count', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('contract_version', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'run_id', name='uq_run_per_pipeline')
    )
    op.create_index('ix_runs_pipeline_started', 'pipeline_runs', ['pipeline_id', 'started_at'], unique=False)
    op.create_table('check_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('check_type', sa.Enum('SOURCE_READABILITY', 'SCHEMA_COMPATIBILITY', 'ROW_COUNT', 'FRESHNESS', name='checktype'), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'SKIPPED', name='checkstatus'), nullable=False),
    sa.Column('expected', sa.JSON(), nullable=True),
    sa.Column('observed', sa.JSON(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_checks_run_type', 'check_results', ['pipeline_run_id', 'check_type'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_definition', sa.JSON(), nullable=False),
    sa.Column('freshness', sa.JSON(), nullable=False),
    sa.Column('quality_rules', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'version', name='uq_contract_version_per_dataset')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('incident_type', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentseverity'), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='incidentstatus'), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('failure_summary', sa.String(), nullable=True),
    sa.Column('first_observed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_status_owner', 'incidents', ['status', 'owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incidents_status_owner', table_name='incidents')
    op.drop_table('incidents')
    op.drop_table('contracts')
    op.drop_index('ix_checks_run_type', table_name='check_results')
    op.drop_table('check_results')
    op.drop_index('ix_runs_pipeline_started', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_table('datasets')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
